# Generated by Django 3.1.4 on 2020-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='signsImage')),
                ('desc', models.TextField()),
                ('order', models.IntegerField()),
                ('favor', models.BooleanField(default=False)),
            ],
        ),
    ]
