# Generated by Django 3.1.4 on 2021-01-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_auto_20201227_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Dectionary',
        ),
    ]
