# Generated by Django 3.1.4 on 2021-01-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_auto_20210104_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dectionary',
            new_name='Dictionary',
        ),
    ]
